version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - db_data:/var/lib/mysql

  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    container_name: laravel
    ports:
      - "8000:80"
    volumes:
      - ./laravel:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=homestead
      - DB_USERNAME=homestead
      - DB_PASSWORD=secret
    depends_on:
      - db

  angular:
    build:
      context: ./angular
      dockerfile: Dockerfile
    container_name: angular
    volumes:
      - ./angular:/app
    working_dir: /app
    command: sh -c "npm install && npm start"
    ports:
      - "4200:4200"
    depends_on:
      - laravel

volumes:
  db_data:
